# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ master ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v2
    
    # Run install
    - name: Install dependencies
      run: npm install

      # Run our deployment command
    - name: Run Prod
      run: npm run prod
      
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        sed -i 's/dist/none/g' .gitignore
      
      # Run our deployment command
    - name: Git commit files
      run: git add . && git commit -m "Deploy files"

    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: npm run deploy
